services:
  db:
    image: postgres:15
    container_name: smart_traffic_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: smart_traffic
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d smart_traffic"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: smart_traffic_rmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: always

  backend:
    build: ./services/backend-api
    container_name: smart_traffic_backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://admin:adminpassword@db:5432/smart_traffic
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - BACKEND_NOTIFY_URL=http://localhost:3000/api/violations/notify-realtime
    volumes:
      - ./services/backend-api/public:/app/public
      - ./services/ai-service/videos:/app/videos
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always

  frontend:
    build: ./services/frontend-dashboard
    container_name: smart_traffic_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api
    volumes:
      - ./services/frontend-dashboard:/app            # ← Mount code
      - /app/node_modules                              # ← Giữ node_modules của container
    depends_on:
      - backend
    restart: always

  ai:
    build: ./services/ai-service
    container_name: smart_traffic_ai
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - VIDEO_DIR=/app/videos              # ← MỚI
      - VIDEO_PATH=                        # ← ĐỂ RỖNG
      - YOLO_CONFIG_DIR=/tmp/Ultralytics
      - PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK=True
    volumes:
      - ./services/ai-service:/app
      - ./models/paddleocr:/root/.paddleocr
      - ./models/paddlex:/root/.paddlex
    depends_on:
      rabbitmq:
        condition: service_healthy
      backend:
        condition: service_started
    restart: on-failure