version: '3.8'

services:
  db:
    image: postgres:15
    container_name: smart_traffic_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: smart_traffic
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: smart_traffic_rmq
    ports:
      - "5672:5672"   # Port chính để ứng dụng Node.js kết nối
      - "15672:15672" # Port dành cho giao diện web quản lý Dashboard của RabbitMQ
    restart: always

  backend:
    build: ./services/backend-api
    container_name: smart_traffic_backend
    ports:
      - "3000:3000"
    environment:
      # Chú ý: Đổi chữ 'localhost' thành chữ 'db' để Backend tìm được container Database
      - DATABASE_URL=postgres://admin:adminpassword@db:5432/smart_traffic
    depends_on:
      - db
      - rabbitmq
    restart: always